"""empty message

Revision ID: 7515421af93f
Revises: 30fcdbac532e
Create Date: 2018-05-11 10:49:10.753547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7515421af93f'
down_revision = '30fcdbac532e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.drop_constraint('auto_case_ibfk_2', 'auto_case', type_='foreignkey')
    op.drop_constraint('auto_element_ibfk_2', 'auto_element', type_='foreignkey')
    op.drop_constraint('auto_keyword_ibfk_2', 'auto_keyword', type_='foreignkey')
    op.drop_constraint('auto_object_ibfk_2', 'auto_object', type_='foreignkey')
    op.drop_constraint('auto_project_ibfk_2', 'auto_project', type_='foreignkey')
    op.drop_constraint('auto_step_ibfk_1', 'auto_step', type_='foreignkey')
    op.drop_constraint('auto_suite_ibfk_2', 'auto_suite', type_='foreignkey')
    op.drop_constraint('auto_task_ibfk_2', 'auto_task', type_='foreignkey')
    op.drop_constraint('auto_variable_ibfk_2', 'auto_variable', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('auto_variable_ibfk_2', 'auto_variable', 'auto_object', ['object_id'], ['id'])
    op.create_foreign_key('auto_task_ibfk_2', 'auto_task', 'auto_project', ['project_id'], ['id'])
    op.create_foreign_key('auto_suite_ibfk_2', 'auto_suite', 'auto_project', ['project_id'], ['id'])
    op.create_foreign_key('auto_step_ibfk_1', 'auto_step', 'auto_case', ['case_id'], ['id'])
    op.create_foreign_key('auto_project_ibfk_2', 'auto_project', 'auto_product', ['product_id'], ['id'])
    op.create_foreign_key('auto_object_ibfk_2', 'auto_object', 'auto_project', ['project_id'], ['id'])
    op.create_foreign_key('auto_keyword_ibfk_2', 'auto_keyword', 'auto_object', ['object_id'], ['id'])
    op.create_foreign_key('auto_element_ibfk_2', 'auto_element', 'auto_object', ['object_id'], ['id'])
    op.create_foreign_key('auto_case_ibfk_2', 'auto_case', 'auto_suite', ['suite_id'], ['id'])
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
