"""empty message

Revision ID: 8028da6926a7
Revises: 
Create Date: 2018-05-03 14:08:26.690292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8028da6926a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('auto_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.String(length=64), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('create_author_id', sa.Integer(), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.Column('update_author_id', sa.Integer(), nullable=True),
    sa.Column('update_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['update_author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_product_create_timestamp'), 'auto_product', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_auto_product_desc'), 'auto_product', ['desc'], unique=False)
    op.create_index(op.f('ix_auto_product_enable'), 'auto_product', ['enable'], unique=False)
    op.create_index(op.f('ix_auto_product_name'), 'auto_product', ['name'], unique=False)
    op.create_index(op.f('ix_auto_product_tags'), 'auto_product', ['tags'], unique=False)
    op.create_index(op.f('ix_auto_product_update_timestamp'), 'auto_product', ['update_timestamp'], unique=False)
    op.create_table('auto_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.String(length=64), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('cron', sa.Text(), nullable=True),
    sa.Column('setup', sa.Text(), nullable=True),
    sa.Column('teardown', sa.Text(), nullable=True),
    sa.Column('create_author_id', sa.Integer(), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.Column('update_author_id', sa.Integer(), nullable=True),
    sa.Column('update_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['auto_product.id'], ),
    sa.ForeignKeyConstraint(['update_author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_project_category'), 'auto_project', ['category'], unique=False)
    op.create_index(op.f('ix_auto_project_create_timestamp'), 'auto_project', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_auto_project_desc'), 'auto_project', ['desc'], unique=False)
    op.create_index(op.f('ix_auto_project_enable'), 'auto_project', ['enable'], unique=False)
    op.create_index(op.f('ix_auto_project_name'), 'auto_project', ['name'], unique=False)
    op.create_index(op.f('ix_auto_project_tags'), 'auto_project', ['tags'], unique=False)
    op.create_index(op.f('ix_auto_project_update_timestamp'), 'auto_project', ['update_timestamp'], unique=False)
    op.create_index(op.f('ix_auto_project_version'), 'auto_project', ['version'], unique=False)
    op.create_table('auto_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('prev', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.String(length=64), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('setup', sa.Text(), nullable=True),
    sa.Column('teardown', sa.Text(), nullable=True),
    sa.Column('create_author_id', sa.Integer(), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.Column('update_author_id', sa.Integer(), nullable=True),
    sa.Column('update_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['auto_project.id'], ),
    sa.ForeignKeyConstraint(['update_author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_object_category'), 'auto_object', ['category'], unique=False)
    op.create_index(op.f('ix_auto_object_create_timestamp'), 'auto_object', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_auto_object_desc'), 'auto_object', ['desc'], unique=False)
    op.create_index(op.f('ix_auto_object_enable'), 'auto_object', ['enable'], unique=False)
    op.create_index(op.f('ix_auto_object_name'), 'auto_object', ['name'], unique=False)
    op.create_index(op.f('ix_auto_object_tags'), 'auto_object', ['tags'], unique=False)
    op.create_index(op.f('ix_auto_object_update_timestamp'), 'auto_object', ['update_timestamp'], unique=False)
    op.create_table('auto_suite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('prev', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.String(length=64), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('setup', sa.Text(), nullable=True),
    sa.Column('teardown', sa.Text(), nullable=True),
    sa.Column('create_author_id', sa.Integer(), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.Column('update_author_id', sa.Integer(), nullable=True),
    sa.Column('update_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['auto_project.id'], ),
    sa.ForeignKeyConstraint(['update_author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_suite_create_timestamp'), 'auto_suite', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_auto_suite_desc'), 'auto_suite', ['desc'], unique=False)
    op.create_index(op.f('ix_auto_suite_enable'), 'auto_suite', ['enable'], unique=False)
    op.create_index(op.f('ix_auto_suite_name'), 'auto_suite', ['name'], unique=False)
    op.create_index(op.f('ix_auto_suite_tags'), 'auto_suite', ['tags'], unique=False)
    op.create_index(op.f('ix_auto_suite_update_timestamp'), 'auto_suite', ['update_timestamp'], unique=False)
    op.create_table('auto_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('build_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('create_author_id', sa.Integer(), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.Column('end_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['auto_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_task_build_no'), 'auto_task', ['build_no'], unique=False)
    op.create_index(op.f('ix_auto_task_create_timestamp'), 'auto_task', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_auto_task_end_timestamp'), 'auto_task', ['end_timestamp'], unique=False)
    op.create_index(op.f('ix_auto_task_result'), 'auto_task', ['result'], unique=False)
    op.create_index(op.f('ix_auto_task_status'), 'auto_task', ['status'], unique=False)
    op.create_table('auto_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=True),
    sa.Column('prev', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.String(length=64), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('setup', sa.Text(), nullable=True),
    sa.Column('teardown', sa.Text(), nullable=True),
    sa.Column('create_author_id', sa.Integer(), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.Column('update_author_id', sa.Integer(), nullable=True),
    sa.Column('update_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['auto_suite.id'], ),
    sa.ForeignKeyConstraint(['update_author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_case_create_timestamp'), 'auto_case', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_auto_case_desc'), 'auto_case', ['desc'], unique=False)
    op.create_index(op.f('ix_auto_case_enable'), 'auto_case', ['enable'], unique=False)
    op.create_index(op.f('ix_auto_case_name'), 'auto_case', ['name'], unique=False)
    op.create_index(op.f('ix_auto_case_tags'), 'auto_case', ['tags'], unique=False)
    op.create_index(op.f('ix_auto_case_update_timestamp'), 'auto_case', ['update_timestamp'], unique=False)
    op.create_table('auto_element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('prev', sa.Integer(), nullable=True),
    sa.Column('element', sa.Text(), nullable=True),
    sa.Column('create_author_id', sa.Integer(), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.Column('update_author_id', sa.Integer(), nullable=True),
    sa.Column('update_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['auto_object.id'], ),
    sa.ForeignKeyConstraint(['update_author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_element_create_timestamp'), 'auto_element', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_auto_element_update_timestamp'), 'auto_element', ['update_timestamp'], unique=False)
    op.create_table('auto_keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('prev', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.Text(), nullable=True),
    sa.Column('create_author_id', sa.Integer(), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.Column('update_author_id', sa.Integer(), nullable=True),
    sa.Column('update_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['auto_object.id'], ),
    sa.ForeignKeyConstraint(['update_author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_keyword_create_timestamp'), 'auto_keyword', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_auto_keyword_update_timestamp'), 'auto_keyword', ['update_timestamp'], unique=False)
    op.create_table('auto_variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('prev', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('create_author_id', sa.Integer(), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.Column('update_timestamp', sa.DateTime(), nullable=True),
    sa.Column('update_author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['create_author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['auto_object.id'], ),
    sa.ForeignKeyConstraint(['update_author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_variable_category'), 'auto_variable', ['category'], unique=False)
    op.create_index(op.f('ix_auto_variable_create_timestamp'), 'auto_variable', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_auto_variable_desc'), 'auto_variable', ['desc'], unique=False)
    op.create_index(op.f('ix_auto_variable_name'), 'auto_variable', ['name'], unique=False)
    op.create_index(op.f('ix_auto_variable_update_timestamp'), 'auto_variable', ['update_timestamp'], unique=False)
    op.create_table('auto_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('prev', sa.Integer(), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.Column('keyword', sa.String(length=128), nullable=True),
    sa.Column('param_1', sa.String(length=128), nullable=True),
    sa.Column('param_2', sa.String(length=128), nullable=True),
    sa.Column('param_3', sa.String(length=128), nullable=True),
    sa.Column('param_4', sa.String(length=128), nullable=True),
    sa.Column('step', sa.Text(), nullable=True),
    sa.Column('create_author_id', sa.Integer(), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.Column('update_author_id', sa.Integer(), nullable=True),
    sa.Column('update_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['auto_case.id'], ),
    sa.ForeignKeyConstraint(['create_author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['update_author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_step_create_timestamp'), 'auto_step', ['create_timestamp'], unique=False)
    op.create_index(op.f('ix_auto_step_desc'), 'auto_step', ['desc'], unique=False)
    op.create_index(op.f('ix_auto_step_enable'), 'auto_step', ['enable'], unique=False)
    op.create_index(op.f('ix_auto_step_keyword'), 'auto_step', ['keyword'], unique=False)
    op.create_index(op.f('ix_auto_step_param_1'), 'auto_step', ['param_1'], unique=False)
    op.create_index(op.f('ix_auto_step_param_2'), 'auto_step', ['param_2'], unique=False)
    op.create_index(op.f('ix_auto_step_param_3'), 'auto_step', ['param_3'], unique=False)
    op.create_index(op.f('ix_auto_step_param_4'), 'auto_step', ['param_4'], unique=False)
    op.create_index(op.f('ix_auto_step_update_timestamp'), 'auto_step', ['update_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_step_update_timestamp'), table_name='auto_step')
    op.drop_index(op.f('ix_auto_step_param_4'), table_name='auto_step')
    op.drop_index(op.f('ix_auto_step_param_3'), table_name='auto_step')
    op.drop_index(op.f('ix_auto_step_param_2'), table_name='auto_step')
    op.drop_index(op.f('ix_auto_step_param_1'), table_name='auto_step')
    op.drop_index(op.f('ix_auto_step_keyword'), table_name='auto_step')
    op.drop_index(op.f('ix_auto_step_enable'), table_name='auto_step')
    op.drop_index(op.f('ix_auto_step_desc'), table_name='auto_step')
    op.drop_index(op.f('ix_auto_step_create_timestamp'), table_name='auto_step')
    op.drop_table('auto_step')
    op.drop_index(op.f('ix_auto_variable_update_timestamp'), table_name='auto_variable')
    op.drop_index(op.f('ix_auto_variable_name'), table_name='auto_variable')
    op.drop_index(op.f('ix_auto_variable_desc'), table_name='auto_variable')
    op.drop_index(op.f('ix_auto_variable_create_timestamp'), table_name='auto_variable')
    op.drop_index(op.f('ix_auto_variable_category'), table_name='auto_variable')
    op.drop_table('auto_variable')
    op.drop_index(op.f('ix_auto_keyword_update_timestamp'), table_name='auto_keyword')
    op.drop_index(op.f('ix_auto_keyword_create_timestamp'), table_name='auto_keyword')
    op.drop_table('auto_keyword')
    op.drop_index(op.f('ix_auto_element_update_timestamp'), table_name='auto_element')
    op.drop_index(op.f('ix_auto_element_create_timestamp'), table_name='auto_element')
    op.drop_table('auto_element')
    op.drop_index(op.f('ix_auto_case_update_timestamp'), table_name='auto_case')
    op.drop_index(op.f('ix_auto_case_tags'), table_name='auto_case')
    op.drop_index(op.f('ix_auto_case_name'), table_name='auto_case')
    op.drop_index(op.f('ix_auto_case_enable'), table_name='auto_case')
    op.drop_index(op.f('ix_auto_case_desc'), table_name='auto_case')
    op.drop_index(op.f('ix_auto_case_create_timestamp'), table_name='auto_case')
    op.drop_table('auto_case')
    op.drop_index(op.f('ix_auto_task_status'), table_name='auto_task')
    op.drop_index(op.f('ix_auto_task_result'), table_name='auto_task')
    op.drop_index(op.f('ix_auto_task_end_timestamp'), table_name='auto_task')
    op.drop_index(op.f('ix_auto_task_create_timestamp'), table_name='auto_task')
    op.drop_index(op.f('ix_auto_task_build_no'), table_name='auto_task')
    op.drop_table('auto_task')
    op.drop_index(op.f('ix_auto_suite_update_timestamp'), table_name='auto_suite')
    op.drop_index(op.f('ix_auto_suite_tags'), table_name='auto_suite')
    op.drop_index(op.f('ix_auto_suite_name'), table_name='auto_suite')
    op.drop_index(op.f('ix_auto_suite_enable'), table_name='auto_suite')
    op.drop_index(op.f('ix_auto_suite_desc'), table_name='auto_suite')
    op.drop_index(op.f('ix_auto_suite_create_timestamp'), table_name='auto_suite')
    op.drop_table('auto_suite')
    op.drop_index(op.f('ix_auto_object_update_timestamp'), table_name='auto_object')
    op.drop_index(op.f('ix_auto_object_tags'), table_name='auto_object')
    op.drop_index(op.f('ix_auto_object_name'), table_name='auto_object')
    op.drop_index(op.f('ix_auto_object_enable'), table_name='auto_object')
    op.drop_index(op.f('ix_auto_object_desc'), table_name='auto_object')
    op.drop_index(op.f('ix_auto_object_create_timestamp'), table_name='auto_object')
    op.drop_index(op.f('ix_auto_object_category'), table_name='auto_object')
    op.drop_table('auto_object')
    op.drop_index(op.f('ix_auto_project_version'), table_name='auto_project')
    op.drop_index(op.f('ix_auto_project_update_timestamp'), table_name='auto_project')
    op.drop_index(op.f('ix_auto_project_tags'), table_name='auto_project')
    op.drop_index(op.f('ix_auto_project_name'), table_name='auto_project')
    op.drop_index(op.f('ix_auto_project_enable'), table_name='auto_project')
    op.drop_index(op.f('ix_auto_project_desc'), table_name='auto_project')
    op.drop_index(op.f('ix_auto_project_create_timestamp'), table_name='auto_project')
    op.drop_index(op.f('ix_auto_project_category'), table_name='auto_project')
    op.drop_table('auto_project')
    op.drop_index(op.f('ix_auto_product_update_timestamp'), table_name='auto_product')
    op.drop_index(op.f('ix_auto_product_tags'), table_name='auto_product')
    op.drop_index(op.f('ix_auto_product_name'), table_name='auto_product')
    op.drop_index(op.f('ix_auto_product_enable'), table_name='auto_product')
    op.drop_index(op.f('ix_auto_product_desc'), table_name='auto_product')
    op.drop_index(op.f('ix_auto_product_create_timestamp'), table_name='auto_product')
    op.drop_table('auto_product')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
